### ISSUE TITLE
networking issue when ported to Docker

### ISSUE THREAD

**Issue by aisuneko** [itkach/aard2-web#12]
I'm trying to port your app to Docker, but it seems that the container's port isn't properly published to localhost, as mentioned [here](https://stackoverflow.com/questions/68677531/how-to-properly-expose-publish-ports-for-a-webui-based-application-in-docker). Are there any workaround for this? Thanks!

**Comment by itkach** [comment]
you need to tell the server to listen on all network interfaces instead of localhost - that is you are missing ` -Dslobber.host=0.0.0.0`

this works for me:
```
FROM anapsix/alpine-java
COPY ./build/libs/aard2-web-0.7.jar /home/aard2-web-0.7.jar
CMD ["bash", "-c", "java -Dslobber.host=0.0.0.0 -jar /home/aard2-web-0.7.jar /dicts/*.slob"]
EXPOSE 8013/tcp
```

and then run like this:

```
docker run -v $HOME/Downloads:/dicts -p 8013:8013 --rm aard2-web
```

`-Dslobber.browse=true` opens default browser, I don't think this has any effect in docker so don't need that.
