### ISSUE TITLE
Files favicon.ico and styleswitcher.js are missing

### ISSUE THREAD

**Issue by AndrewDevAndroid** [itkach/aard2-web#3]
I'd repair javascript error by added missing files to repository, its was
extracted from jar-file.
But I have no permissions to send pool request. I commit to new local branch and try to create pull request, but official Github client says "You have no permission to push your changes to this repository". Maybe I do something wrong? I'm novice at Github and would try to work in other Aard repositories.
![1](https://cloud.githubusercontent.com/assets/3532788/9848528/9d6d880e-5aea-11e5-9425-da89bea86dd1.png)

**Comment by itkach** [comment]
> I'd repair javascript error by added missing files to repository, its was
> extracted from jar-file.

I am not sure what problem are you trying to solve. `favicon.ico` and `styleswitcher.js` are in aard2-web jar file and are served just fine. These resources come from [slobber](https://github.com/itkach/slobber).

> But I have no permissions to send pool request.

It looks like you are are trying to push your changes to my repository (hence no permission). You should have cloned it and pushed changes to your repository and then you'd be able to create pull request.

You may want to familiarize yourself with git command line interface - UI front-ends may be handy but they also tend to obscure what's going on.

**Comment by martynbm** [comment]
Git pull Gerrit makefile

**Comment by martynbm** [comment]
Push
